# Generated by Django 2.1.5 on 2019-06-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsschool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='maximum_score',
            field=models.FloatField(default=0),
        ),
    ]
