# Generated by Django 2.1.5 on 2019-05-26 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpsschool', '0002_auto_20190401_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='subjects',
            new_name='subject',
        ),
    ]
