# Generated by Django 2.1.5 on 2019-06-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsschool', '0002_task_maximum_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
