# Generated by Django 2.1.5 on 2019-06-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsschool', '0003_payments_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentschedule',
            name='transactions',
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='transactions',
            field=models.ManyToManyField(to='gpsschool.Payments'),
        ),
    ]
