# Generated by Django 2.1.5 on 2019-06-08 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpsschool', '0005_auto_20190607_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpsschool.Student'),
        ),
    ]
