# Generated by Django 2.1.5 on 2019-06-09 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpsschool', '0006_task_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='standard',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gpsschool.Standard'),
        ),
    ]
