# Generated by Django 2.1.5 on 2019-06-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsschool', '0008_auto_20190609_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
