# Generated by Django 2.1.5 on 2019-06-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsschool', '0012_auto_20190609_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentschedule',
            name='scholarship_type',
            field=models.CharField(choices=[('00', 'None'), ('01', 'RTE'), ('02', 'Second type'), ('03', 'Third type')], default=None, max_length=2),
        ),
    ]
