# Generated by Django 2.1.5 on 2019-06-09 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpsschool', '0013_auto_20190609_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gpsschool.Subject'),
        ),
    ]
